### ISSUE TITLE
irclib has a rare case of crashing.

### ISSUE THREAD

**Issue by Wessie** [R-a-dio/Hanyuu-sama#56]
Full exception:

```
Exception in thread IRC Processor:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "irc.py", line 50, in processor
    self._irc.process_once(timeout=1)
  File "/home/hanyuu/Hanyuu-sama/irclib.py", line 247, in process_once
    self.process_data(i)
  File "/home/hanyuu/Hanyuu-sama/irclib.py", line 188, in process_data
    c.process_data()
  File "/home/hanyuu/Hanyuu-sama/irclib.py", line 646, in process_data
    self.sqlite.quit(nm_to_n(prefix))
  File "/home/hanyuu/Hanyuu-sama/irclib.py", line 1089, in quit
    self.part(chan, nick)
  File "/home/hanyuu/Hanyuu-sama/irclib.py", line 1074, in part
    cur.execute("SELECT * FROM nick_chan_link WHERE chan_id=?", (chan_id,))
InterfaceError: Error binding parameter 0 - probably unsupported type.
```

it most likely is receiving `None` and doesn't handle this case.

**Comment by Bevinsky** [comment]
I've examined this and I've come to the conclusion that this exception actually can't happen. Yes, that's right, it can't happen. And I can't fix exceptions that can't happen.

**Comment by Wessie** [comment]
Closed, can't reproduce.
