### ISSUE TITLE
When lastfm is down, hanyuu throws an exception instead of handling it gracefully

### ISSUE THREAD

**Issue by Bevinsky** [R-a-dio/Hanyuu-sama#57]
```
ERROR:root:Error in lastfm listen handler
Traceback (most recent call last):
  File "/home/hanyuu/Hanyuu-sama/hanyuu_commands.py", line 597, in lastfm_listening
    np = user.get_now_playing()
  File "/usr/local/lib/python2.7/dist-packages/pylast.py", line 2885, in get_now_playing
    doc = self._request('user.getRecentTracks', False, params)
  File "/usr/local/lib/python2.7/dist-packages/pylast.py", line 970, in _request
    return _Request(self.network, method_name, params).execute(cacheable)
  File "/usr/local/lib/python2.7/dist-packages/pylast.py", line 828, in execute
    response = self._download_response()
  File "/usr/local/lib/python2.7/dist-packages/pylast.py", line 817, in _download_response
    raise MalformedResponseError(self.network, e)
MalformedResponseError: Malformed response from Last.fm. Underlying error: ''
```

**Comment by Wessie** [comment]
Did this ever get fixed?
